version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/HSC/HCV_API/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/HSC/HCV_CASJOBS/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/HSC/HSCV3_API/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/HSC/HSCV3_SMC_API/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/HSC/HSC_TAP/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/HSC/SWEEPS_HSCV3P1/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/HSC/SWEEPS_HSCV3P1_API/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/JWST/Engineering_Database_Retreival/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/JWST/SI_keyword_exoplanet_search/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/JWST/download_by_program_id/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/K2/Lightcurve/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/K2/TPF/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/K2/beginner_how_to_use_ffi/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/K2/removing_instrumental_noise_using_pld/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/creating_periodograms/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/how_to_estimate_a_stars_mass_and_radius_using_asteroseismology/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/how_to_understand_and_manipulate_the_periodogram_of_an_oscillating_star/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/identifying_transiting_planet_signals/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/instrumental_noise_1_data_gaps_and_quality_flags/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/instrumental_noise_2_spurious_signals_and_time_sampling_effects/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/instrumental_noise_3_seasonal_and_detector_effects/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/instrumental_noise_4_electronic_noise/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/lightkurve_combining_multiple_quarters/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/lightkurve_custom_aperture_photometry/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/lightkurve_interactively_inspecting_TPFs_and_LCs/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/lightkurve_searching_for_data/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/measuring_a_rotation_period/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/plotting_catalog_over_FFI/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/plotting_dvts/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/plotting_images_from_tpf/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/plotting_lightcurves/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/verifying_the_location_of_a_signal/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/Kepler/visualizing_periodic_signals_using_a_river_plot/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/PanSTARRS/PS1_DR2_TAP/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/beginner_astroquery_dv/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/beginner_how_to_use_dvt/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/beginner_how_to_use_ffi/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/beginner_how_to_use_lc/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/beginner_how_to_use_tp/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/beginner_tess_exomast/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/beginner_tess_tap_search/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/beginner_tesscut_astroquery/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/beginner_tic_search_hd209458/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/beginner_tour_lc_tp/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/interm_gi_query/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/interm_tasoc_lc/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/interm_tess_prf_retrieve/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/interm_tesscut_dss_overlay/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/interm_tesscut_requests/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/TESS/removing_scattered_light_using_regression/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/astrocut/making_tess_cubes_and_cutouts/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/astroquery/beginner_search/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/astroquery/beginner_zcut/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/astroquery/large_downloads/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
