name: Section 508 compliance check
on:
  workflow_dispatch:
jobs:
  a11yWatchRun:
    uses: dulude/notebook-ci-actions/.github/workflows/html_accessibility_check.yml@main
    with:
      target_url: https://spacetelescope.github.io/${{ github.event.repository.name }}/intro.html
